---   
- debug:
    msg: "{{ grafana_datasources }}"

- name: Ensure datasources exist (via API)
  grafana_datasource:
    grafana_url: "{{ grafana_api_url }}"
    grafana_user: "{{ grafana_security.admin_user }}"
    grafana_password: "{{ grafana_security.admin_password }}"
    name: "{{ item.name }}"
    url: "{{ item.url | default(omit) }}"
    ds_type: "{{ item.type }}"
#    access: "{{ item.access | default(omit) }}"
    database: "{{ item.database | default(omit) }}"
#    is_default: "{{ item.isDefault | default(omit) }}"
    basic_auth_user: "{{ item.basicAuthUser | default(omit) }}"
    basic_auth_password: "{{ item.basicAuthPassword | default(omit) }}"
  with_items: "{{ grafana_datasources }}"
  ignore_errors: yes