--- 
- name: create /media/usb
  file:
    path: /media/usb
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  
- name: Mount up device by label DATA
  mount:
    path: /media/usb
    src: LABEL=DATA
    fstype: vfat
    opts: auto,nofail,noatime,users,rw,uid=pi,gid=pi
    state: mounted
  become: true
  become_user: pi  
   
- name: Create symbolic link to /var/docker-compose/data
  file:
    src: /media/usb
    path: /var/docker-compose/data
    state: link
    mode: 0755
    owner: pi
    group: pi  

- name: Create symbolic link to /data
  file:
    src: /var/docker-compose/data
    path: /data
    state: link
    mode: 0755
    owner: pi
    group: pi  

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 04EE7237B7D453EC

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 648ACFD622F3D138

- name: Add buster-backports to /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: deb http://deb.debian.org/debian buster-backports main    

- name: apt-get update
  shell:
    cmd: "apt-get update"

- name: apt-get update
  shell:
    cmd: "apt install libseccomp2/buster-backports"    

- name: create /var/docker-compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:        
    - "/var/docker-compose/data/mqtt/config"
#    - "/var/docker-compose/data/nginx/html"
#    - "/var/docker-compose/data/nginx/sites-enabled"    
#    - "/var/docker-compose/data/dsmrdb/etc"
#    - "/var/docker-compose/data/dsmrdb/postgresql"   
    - "/var/docker-compose/data/dsmr/config"
    - "/var/docker-compose/data/dsmr/dsmr_backups"
#    - "/var/docker-compose/data/dsmr/dsmr_backups"
    - "/var/docker-compose/data/dsmrdb/data"
    - "/var/docker-compose/data/dsmrdb/dsmr_backups"

- name: copy Docker Compose files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-compose"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/docker/*"

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "files/data/mqtt/config/mosquitto.conf", dest: "/var/docker-compose/data/mqtt/config/mosquitto.conf" }
  - { src: "files/data/mqtt/config/passwords.mqtt", dest: "/var/docker-compose/data/mqtt/config/passwords.mqtt" }
#  - { src: "files/data/nginx/html/index.html", dest: "/var/docker-compose/data/nginx/html/index.html" }
#  - { src: "files/data/nginx/html/schuur.jpg", dest: "/var/docker-compose/data/nginx/html/schuur.jpg" }
#  - { src: "files/data/nginx/html/schuur.png", dest: "/var/docker-compose/data/nginx/html/schuur.png" }
#  - { src: "files/data/nginx/sites-enabled/default", dest: "/var/docker-compose/data/nginx/sites-enabled/default" }
  - { src: "files/data/dsmr/config/supervisord.conf",  dest: "/var/docker-compose/data/dsmr/config/supervisord.conf" }
  - { src: "files/data/dsmr/config/bashrc",  dest: "/var/docker-compose/data/dsmr/config/bashrc" }
  
- name: deploy Docker Compose stack
  shell:
    cmd: "docker-compose up -d"
  args:
    chdir:  /var/docker-compose
  become: pi