---
- name: create /var/docker-compose
  file:
    path: "{{ item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
    - "/var/docker-compose"
  
- name: copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /var/docker-compose/{{ item }}
    mode: 0755
    owner: pi
    group: pi
  loop:
  - docker-compose.yml  

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: /var/docker-compose
    files:
    - docker-compose.yml
    