---
- name: install x11
  shell:
    cmd: "curl -sSL https://github.com/hypriot/x11-on-HypriotOS/raw/master/install-x11-basics.sh | bash"
  args:
    chdir: /var/tmp

- name: update /etc/lightdm/lightdm.conf
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    line: "xserver-allow-tcp=true"
    state: present  

- name: update /etc/X11/Xsession.d/36x11-xhost-docker
  lineinfile:
    dest: /etc/X11/Xsession.d/36x11-xhost-docker
    line: "xhost +e"
    state: present  
