---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Check for /var/lcd_installed
  stat:
    path: /var/lcd_installed
  register: p

- name: apt-get update
  shell:
    cmd: "apt-get update"

- name: Execute only once
  block:
  - name: update /boot/config.txt
    lineinfile:
      dest: /boot/config.txt
      line: "display_rotate=0"
      state: present  
  
  - name: install x11 1
    apt: 
      name: [ "xserver-xorg", "xinit", "xserver-xorg-video-fbdev", "lxde", "lxde-common", "lightdm", "x11-xserver-utils" ]
      install_recommends: no

  - name: install x11 2
    apt: 
      name: [ "policykit-1" ]
      install_recommends: no

 ## - name: download pre-compiled fbturbo
 ##   get_url:
 ##     url: https://github.com/hypriot/x11-on-HypriotOS/raw/master/fbturbo/fbturbo.tar.gz
 ##     dest: /tmp
 ##     mode: 0760

 ## - name: untar
 ##   shell: |
 ##     tar xvf fbturbo.tar.gz -C /
 ##   args:
 ##     chdir: /tmp

 ## - name: clean
 ##   file:
 ##     path: "/tmp/fbturbo.tar.gz"
 ##     state: absent
 ##   ignore_errors: yes

#  - name: update /etc/lightdm/lightdm.conf
#    lineinfile:
#      dest: /etc/lightdm/lightdm.conf
#      line: "xserver-allow-tcp=true"
#      state: present  

#  - name: update /etc/lightdm/lightdm.conf
#    lineinfile:
#      dest: /etc/lightdm/lightdm.conf
#      line: "allow-tcp=true"
#      state: present  

  - name: update /etc/X11/Xsession.d/36x11-xhost-docker
    lineinfile:
      dest: /etc/X11/Xsession.d/36x11-xhost-docker
      line: "xhost +e"
      state: present  
      create: yes

  - name: Touch /var/lcd_installed
    file:
      path: /var/lcd_installed
      state: touch
      mode: 755

  - name: Check for lcd-show exists in /opt
    stat:
      path: /opt/lcd-show
    register: p1

  - name: download LCD-show
    git:
      repo: https://github.com/goodtft/LCD-show.git
      dest: /opt/lcd-show
      force: yes
    when: not p1.stat.exists

  - name: chmod /opt/lcd-show
    file:
      path: /opt/lcd-show
      recurse: yes
      mode: 0755
      owner: pi
      group: pi
    when: not p1.stat.exists

  - name: write LightDM configuration
    become: yes
    template:
      src: lightdm.conf.j2
      dest: '/etc/lightdm/lightdm.conf'
      owner: root
      group: root
      mode: 'u=rw,go=r'

  - name: HDMI output to LCD screen
    shell:
      cmd: "./MHS40-show"
    args:
      chdir: /opt/lcd-show
  when: not p.stat.exists
  
- name: HDMI output to LCD screen
  shell:
    cmd: "update-rc.d lightdm disable"

- name: dpkg-reconfigure lightdm
  shell:
    cmd: "dpkg-reconfigure lightdm"




#- name: Copy screen.sh
#  template:
#    src: "screen.sh"
#    dest: "/home/pi/screen.sh"
#    owner: pi
#    group: pi
#    mode: 0644   

#- name: Copy screen.service
#  copy:
#    src: "screen.service"
#    dest: "/lib/systemd/system/screen.service"
#    owner: pi
#    group: pi
#    mode: 0644   

#- name: screen.service
#  service:
#    name: screen.service
#    state: started
#    enabled: yes    


- name: Copy file 99-fbdev.conf
  copy:
    src: 99-fbdev.conf
    dest: /usr/share/X11/xorg.conf.d
      