version: '3'
services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    volumes:
      - ./data/dsmrdb/data:/var/lib/postgresql/data
      - ./data/dsmrdb/dsmrdb_backups:/dsmr/backups
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=admin@localhost.nl
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0