version: '3'
services:  
#  weba:
#    image: hypriot/rpi-node:0.12.0
#    volumes:
#    - ./data/webserver/weba:/data
#    ports:
#      - 8080:80
#    command: sh -c "npm install && node index.js"

#  haproxy:
#    image: hypriot/rpi-haproxy
#    volumes:
#    - ./data/haproxy:/haproxy
#    links:
#    - weba
#    ports:
#    - "80:80"
#    - "70:70"
#    expose:
#    - "80"
#    - "70"
  node-red:
    image: nodered/node-red:latest-minimal
    entrypoint: /data/entrypoint.sh
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red:/data
    depends_on:
      - mqtt
      - zigbee
    restart: always
  mqtt:
    image: "eclipse-mosquitto:latest"
    environment:
      - TZ=Europe/Amsterdam
      - "MQTT_BROKER_URL=mqtt://mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    user: "1000:1000"
    volumes:
      - ./data/mqtt/config:/mosquitto/config
      - ./data/mqtt/data:/mosquitto/data
      - ./data/mqtt/log:/mosquitto/log
    restart: always
    
  zigbee:
    image: koenkk/zigbee2mqtt
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/zigbee:/app/data
    depends_on:
      - mqtt
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    network_mode: host
    privileged: true
    restart: always
#  homeassistant:
#    container_name: home-assistant
#    image: homeassistant/home-assistant:stable
#    volumes:
#      - ./data/home-assistant:/config
#    environment:
#      - TZ=Europe/Amsterdam
#    network_mode: host