---
- name: Install redis-server python3
  apt:
    name: [ "redis-server", "python3" ]
    state: present
    update_cache: yes

- name: "python3 -m pip install --upgrade pip"
  shell:
    cmd: "python3 -m pip install --upgrade pip"

- name: "systemctl enable redis.service"
  systemd:
    state: started
    enabled: yes
    name: redis

- name: "pip3 platypush (and others)"
  shell:
    cmd: "pip3 install '{{ item }}'"
  with_items:
    - platypush
    - platypush[zigbee]
    - platypush[http]
    - platypush[mqtt]
    - numpy
    - camera

- name: Creates directory /home/pi/.config/platypush
  file:
    path: /home/pi/.config/platypush
    state: directory
    mode: 0760
    owner: pi
    group: pi

- name: Copy file /home/pi/.config/platypush/config.yaml
  copy:
    src: config.yaml
    dest: /home/pi/.config/platypush/config.yaml

- name: Copy file /etc/systemd/system/platypush.service
  copy:
    src: platypush.service
    dest: /etc/systemd/system/platypush.service

- name: "systemctl enable platypush.service"
  systemd:
    state: started
    enabled: yes
    name: platypush