---
- hosts: rpi
  become_user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles: 
  - role: local
    vars:
      system_hostname: docker
  - role: lcd
  - role: docker
  - role: reboot
