---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local
  - role: nodered
  - role: node-red-adds
  - role: node-red-flows
    vars:
        flow: 'Zigbee.json'
  - role: nginx
  