---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local
    vars:
      servername: nodered
  - role: nodered
  - role: node-red-adds
  - role: node-red-flows
    vars:
        flow: 'nodered.json'
  - role: nginx
  