---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local  
    vars:
      system_hostname: zigbee
  - role: mosquitto
  - role: nodered
  - role: node-red-adds
  - role: node-red-flows
    vars:
        flow: 'zigbee.json'
  - role: nginx
  - role: zigbee2mqtt
  
  