---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local  
  - role: mosquitto
  - role: nodered
  - role: node-red-adds
  - role: node-red-flows
  - role: nginx
  - role: Zigbee2mqtt
  