---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local  
    vars:
      servername: zigbee
  - role: mosquitto
  - role: nodered
  - role: node-red-adds
  - role: node-red-flows
    vars:
        flow: 'Zigbee.json'
  - role: nginx
  - role: Zigbee2mqtt
  