{
 "title": "mydashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Huidige opgewekte stroom",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "query": "SELECT sum(\"ac_output_amps_1\"), sum(\"ac_output_amps_2\"), sum(\"ac_output_amps_3\") FROM \"PV\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stroom verbruik",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "P" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "p1",
     "query": "SELECT mean(\"G\") FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "G" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Temparature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Inverter Temperature (c)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Beste Dagen",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "Generated",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laatste Dagen",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "alias": "Generated",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter AC Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC Frequency (Hz)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "limit": "1",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "weather_icon" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tempratuur",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind snelheid",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "velocityms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Month Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Last month energy (W)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "detailed_status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vandaag opgewekt",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today vs Yesterday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "DC 1 A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "DC Current 1 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC 2 A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "DC Current 2 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC 1 V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "DC Voltage 1 (V)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC 2 V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "DC Voltage 2 (V)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Voltage 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC voltage 1 (V)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Voltage 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC voltage 2 (V)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Voltage 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC voltage 3 (V)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vermogen 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC Current 1 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vermogen 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC Current 2 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vermogen 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC Current 3 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stroom gebruik",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "+P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "+P1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "+P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "+P2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "+P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "+P3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "-P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "-P1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "-P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "-P2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "-P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "-P3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "p1",
     "query": "SELECT mean(\"G\") FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "G" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vochtigheid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sterkte",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zon positie",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "hz" }
   ],
   "targets": [
    {
     "alias": "AC Frequency",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "AC Frequency (Hz)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tempratuur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Tempratuur",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zon hoogte",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "sun_altitude"
    }
   ]
  },
  {
   "title": "uvi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "uvi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "uvi" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generated per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Dag",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Generated (Today)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Tempratuur Inverter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs485",
     "select": [
      [
       { "params": [ "Inverter Temperature (c)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water verbruik",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "watermeter",
     "select": [
      [
       { "params": [ "pulse_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "watermeter",
     "query": "SELECT mean(\"pulse_count\") FROM \"watermeter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pulse_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generated per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Teruglevering",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "+P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Energie afname",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "-P1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}