---
- name: install gui applications
  apt: 
    name: [ "xfce4", "xfce4-terminal", "LightDM"]
    install_recommends: yes

- name: Check for lcd-show exists in /opt     
  stat: 
    path: /opt/lcd-show
  register: p  

- name: download LCD-show
  git:
    repo: https://github.com/goodtft/LCD-show.git
    dest: /opt/lcd-show
    force: yes
  when: not p.stat.exists

- name: chmod /opt/lcd-show
  file:
    path: /opt/lcd-show
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  when: not p.stat.exists

- name: write LightDM configuration
  become: yes
  template:
    src: lightdm.conf.j2
    dest: ' /usr/share/lightdm/lightdm.conf.d/70-ansible.conf'
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: HDMI output to LCD screen
  shell:
    cmd: "./LCD35-show"
  args:
    chdir: /opt/lcd-show
  when: not p.stat.exists

- name: HDMI output to LCD screen
  shell:
    cmd: "update-rc.d lightdm disable"
