---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes

- name: Change locale
  shell: "raspi-config nonint do_change_locale {{ locale }}"

- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: Set WiFi country
  shell: "raspi-config nonint do_wifi_country {{ wifi_country }}"

- set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"

- name: Set WiFi credentials
  shell: "raspi-config nonint do_wifi_ssid_passphrase {{ ssid }} {{ pi_password }}"

- name: Remove not used applications
  apt: 
    name: [ "wolfram-engine", "libreoffice*", "scratch2", "scratch" ]
    state: absent
  ignore_errors: yes

- name: updating hostname {{ system_hostname }} (1/2)
  hostname:
    name: "{{ system_hostname }}"
  register: hostname_change

- name: updating hostname {{ system_hostname }} (2/2)
  copy:
    content: "{{ system_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
  register: hostname_change

- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ system_hostname }}"
    backup: true
    state: present   
      