---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes

- name: Change locale
  shell: "raspi-config nonint do_change_locale {{ locale }}"

- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: Remove not used applications
  apt: 
    name: [ "wolfram-engine", "libreoffice*", "scratch2", "scratch", "wolfram-engine", "nuscratch", "sonic-pi", "idle3", "smartsim", "java-common", "minecraft-pi", "libreoffice*"]
    state: absent
  ignore_errors: yes

- name: apt-get clean
  shell:
    cmd: "apt-get clean"
  become: yes
  
- name: apt-get autoremove -y
  shell:
    cmd: "apt-get autoremove -y"
  become: yes
  
- name: include network.yaml
  include_tasks: network.yaml