---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes

- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
    
- name: Remove not used applications
  apt: 
    name: [ "wolfram-engine", "libreoffice*", "oracle-java*", "scratch2", "scratch" ]
    state: absent
  ignore_errors: yes
