---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes

- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
    
- name: Remove not used applications
  apt: 
    name: [ "wolfram-engine", "libreoffice*", "scratch2", "scratch" ]
    state: absent
  ignore_errors: yes

- name: add new servername  to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1.*localhost'
    line: '127.0.0.1 localhost {{ servername }}'
    state: present

- name: change hostname
  shell: |
    'hostnamectl set-hostname "{{ servername }}"'
  
- name: activate hostname
  shell: |
    "systemctl restart avahi-daemon"
    