---
- name: Install avahi-daemon
  apt: 
    name: [ "avahi-daemon" ]

- name: Update boot startup for avahi-daemon
  shell: "update-rc.d avahi-daemon defaults"

- name: Apply the new configuration
  shell: "update-rc.d avahi-daemon defaults" 

- name: Set WiFi country
  shell: "raspi-config nonint do_wifi_country {{ wifi_country }}"
  register: result
  failed_when: result.rc > 1
  
- name: updating hostname {{ system_hostname }} (1/2)
  hostname:
    name: "{{ system_hostname }}"
  register: hostname_change

- name: updating hostname {{ system_hostname }} (2/2)
  copy:
    content: "{{ system_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
  register: hostname_change

- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ system_hostname }}"
    backup: true
    state: present   

- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1{{'\t'}}{{ system_hostname }}"
    backup: true
    state: present      
