---
- name: Copy file Zigbee.json
  copy:
    src: Zigbee.json
    dest: /home/pi/.node-red/flows_raspberrypi.json
    owner: pi
    group: pi
    mode: 0644   

- name: "node-red force-reload"
  shell:
    cmd: "service nodered force-reload"

- name: "node-red stop"
  shell:
    cmd: "service nodered stop"

- name: "node-red start"
  shell:
    cmd: "service nodered start"

  