---
- name: post to flows
  uri:
    url: http://localhost:1880/flows
    method: POST
    body: "{{ lookup('file','Zigbee.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"

- name: "node-red force-reload"
  shell:
    cmd: "service nodered force-reload"

- name: "node-red stop"
  shell:
    cmd: "service nodered stop"

- name: "node-red stop"
  shell:
    cmd: "service nodered start"

- set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"

- name: set credentialSecret
  lineinfile:
    path: /usr/lib/node_modules/node-red/settings.js
    line: 'credentialSecret: "{{ pi_password }}", '
    insertafter: '//credentialSecret: "a-secret-key",'
    create: no
  