---
- name: Copy file Zigbee.json
  copy:
    src: Zigbee.json
    dest: /var/tmp/Zigbee.json
    
- name: post to flows
  uri:
    url: http://localhost:1880/flows
    method: POST
    body: "{{ lookup('file','/var/tmp/Zigbee.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"

- name: "node-red force-reload"
  shell:
    cmd: "service nodered force-reload"

- name: "node-red stop"
  shell:
    cmd: "service nodered stop"

- name: "node-red start"
  shell:
    cmd: "service nodered start"

  