---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: install pre chromium
  apt: 
    name: [ "xdotool", "unclutter", "sed" ]
    install_recommends: yes

- name: update /etc/apt/sources.list
  lineinfile:
    dest: /etc/apt/sources.list
    line: "deb http://ppa.launchpad.net/canonical-chromium-builds/stage/ubuntu vivid main"
    state: present  

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver:  keyserver.ubuntu.com
    id: DB69B232436DAC4B50BDC59E4E1B983C5B393194

- name: apt-get update
  shell:
    cmd: "apt-get update"

- name: install pre chromium
  apt: 
    name: [ "chromium-browser" ]
    install_recommends: yes

- name: Copy screen.sh
  template:
    src: "screen.sh"
    dest: "/home/pi/screen.sh"
    owner: pi
    group: pi
    mode: 0644   

- name: Copy screen.service
  copy:
    src: "screen.service"
    dest: "/lib/systemd/system/screen.service"
    owner: pi
    group: pi
    mode: 0644   

- name: screen.service
  service:
    name: screen.service
    state: started
    enabled: yes
 