---
- name: download zigbee2mqtt
  git:
    repo: https://github.com/Koenkk/zigbee2mqtt.git
    dest: /opt/zigbee2mqtt
    force: yes

- name: chmod zigbee2mqtt
  file:
    path: /opt/zigbee2mqtt
    recurse: yes
    mode: 0760
    owner: pi
    group: pi

- name: install zigbee2mqtt
  shell:
    cmd: "npm install"
  args:
    chdir: /opt/zigbee2mqtt
  ignore_errors: true
  register: cmd_out
  failed_when: cmd_out.rc >= 2

- name: install zigbee2mqtt
  shell:
    cmd: "npm ci --production"
  args:
    chdir: /opt/zigbee2mqtt
  ignore_errors: true
  become_user: pi
  register: cmd_out
  failed_when: cmd_out.rc >= 2

- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: "/opt/zigbee2mqtt/data/{{ item }}"
    owner: pi
    group: pi
    mode: 0644   
  with_items:
    - configuration.yaml
    - devices.yaml

- name: Copy file /etc/systemd/system/zigbee2mqtt.service
  copy:
    src: zigbee2mqtt.service
    dest: /etc/systemd/system/zigbee2mqtt.service

- name: "systemctl enable zigbee2mqtt.service"
  systemd:
    state: started
    enabled: yes
    name: zigbee2mqtt

- name: install node-red-contrib-zigbee2mqtt
  shell:
    cmd: "npm install {{ item }}"
  args:
    chdir: /usr/lib/node_modules/node-red
  with_items:
#    - node-gyp
#    - jquery
#    - typedoc
#    - typescript
    - node-red-contrib-zigbee2mqtt
    - node-red-contrib-zigbee2mqtt-devices
    - node-red-contrib-zblight

- name: "node-red force-reload"
  shell:
    cmd: "service nodered force-reload"

- name: "node-red stop"
  shell:
    cmd: "service nodered stop"

- name: "node-red stop"
  shell:
    cmd: "service nodered start"