---
- name: download zigbee2mqtt
  git:
    repo: https://github.com/Koenkk/zigbee2mqtt.git
    dest: /opt/zigbee2mqtt
    force: yes

- name: chmod zigbee2mqtt
  file:
    path: /opt/zigbee2mqtt
    recurse: yes
    mode: 0760
    owner: pi
    group: pi

- name: install zigbee2mqtt
  shell:
    cmd: "npm install"
  args:
    chdir: /opt/zigbee2mqtt
  ignore_errors: true
  register: cmd_out
  failed_when: cmd_out.rc >= 2

- name: Copy file /etc/systemd/system/zigbee2mqtt.service
  copy:
    src: zigbee2mqtt.service
    dest: /etc/systemd/system/zigbee2mqtt.service

- name: "systemctl enable zigbee2mqtt.service"
  systemd:
    state: started
    enabled: yes
    name: zigbee2mqtt

- name: install node-red-contrib-zigbee2mqtt
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - node-red-contrib-zigbee2mqtt
