---
- name: download zigbee2mqtt
  - git:
    repo: https://github.com/Koenkk/zigbee2mqtt.git/opt/zigbee2mqtt
    dest: /opt/zigbee2mqtt
    mode: 0760
    owner: pi
    group: pi

- name: install zigbee2mqtt  
  shell:
    cmd: "npm install"
  args:
    chdir: /opt/zigbee2mqtt

