---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: "download and install node-red"
  shell:
    cmd: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"
  ignore_errors: true
  register: result
  failed_when: result.rc > 1

- name: Install nodered
  apt:
    name: [ "nodered", "nodejs", "npm", "node-semver"]
    state: present
    install_recommends: yes
    update_cache: yes

- name: npm install npm@latest
  shell: "curl https://www.npmjs.com/install.sh | sudo sh"
  args:
    chdir: /home/pi

- name: "systemctl enable nodered.service"
  systemd:
    state: started
    enabled: yes
    name: nodered

- set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"

- name: Pause for 5 minutes to build app cache
  pause:
    minutes: 1

- name: set credentialSecret pi
  lineinfile:
    path: "/home/pi/.node-red/settings.js"
    line: 'credentialSecret: "{{ pi_password }}", '
    insertafter: '//credentialSecret: "a-secret-key",'
    create: no    

- name: "systemctl enable nodered.service"
  systemd:
    state: started
    enabled: yes
    name: nodered

- name: "npm audit fix"
  shell: "npm audit fix"
  args:
    chdir: /home/pi
