---
- name: Install nodered
  apt:
    name: [ "nodered ", "nodejs", "npm", "node-semver"]
    state: present
    update_cache: yes

- name: npm install npm@latest
  npm:
    name: npm@latest
    global: yes
    state: latest

- name: "systemctl enable nodered.service"
  systemd:
    state: started
    enabled: yes
    name: nodered
