---
- name: Install nodered 
  apt: 
    name: [ "nodered ", "nodejs", "npm", "node-semver"]
    state: present 
    update_cache: yes


- name: install node-RED
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - node-red-contrib-cron

- name: "systemctl enable nodered.service"
  systemd:
    state: started
    enabled: yes
    name: nodered
    