---
- name: "node-red stop"
  shell:
    cmd: "service nodered stop"
    
- name: include ui
  include_tasks: ui.yaml

- name: include scheduling
  include_tasks: scheduling.yaml

- name: include sonoff
  include_tasks: sonoff.yaml

- name: include network
  include_tasks: network.yaml

- name: "node-red force-reload"
  shell:
    cmd: "service nodered force-reload"

- name: "node-red start"
  shell:
    cmd: "service nodered start"