---
- name: install node-red network adds
  shell:
    cmd: "npm install start {{ item }}"
  become_user: pi
  args:
    chdir: /home/pi/.node-red
  with_items:
    - node-red-node-ping 
    - node-red-contrib-dsm
    - node-red-dashboard
