---
- name: install node-red scheduling adds
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
    path: /home/pi/.node-red
  with_items:
    - node-red-contrib-cron
    - node-red-contrib-sunevents
