---
- name: install node-red scheduling adds
  shell:
    cmd: "npm install start {{ item }}"
  become_user: pi
  args:
    chdir: /home/pi/.node-red
  with_items:
    - node-red-contrib-cron
    - node-red-contrib-sunevents
