---
- name: current date time
  debug: 
    msg: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: install node-red ui adds
  shell:
    cmd: "npm install start {{ item }}"
  become_user: pi
  args:
    chdir: /home/pi/.node-red
  with_items:
    - node-red-dashboard
    - node-red-contrib-ui
#    - node-red-contrib-uibuilder
#    - node-red-contrib-ui-led
#    - node-red-contrib-ui-level
#    - node-red-contrib-ui-time-scheduler
#    - node-red-contrib-ui-artless-gauge
#    - node-red-contrib-ui-state-trail


