---
- name: install apache2
  apt: 
    name: [ "apache2", "libapache2-mod-php", "php-mysql", "default-mysql-server", "phpmyadmin" ]
    install_recommends: yes
       
- name: copy webpage files
  copy:
    src: "{{ item }}"
    dest: "/var/www/{{ item }}"
    owner: pi
    group: pi
    mode: 755
  with_fileglob:
    - /files/*

- name: add php to apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: "Include /etc/phpmyadmin/apache.conf"

- name: change port to 8080 apache2 ports.conf
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    line: "Listen 8080"

- name: Create the my.cnf file
  template: 
    src: my.cnf
    dest: /home/pi/my.cnf
    
    
