---
- name: create /var/docker-Compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
    - "/var/docker-Compose/data"
    - "/var/docker-Compose/data/mqtt/config"
    - "/var/docker-Compose/data/zigbee"
    - "/var/docker-Compose/data/node-red"
    - "/var/docker-Compose/data/home-assistant"    

- name: copy Docker Compose files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-Compose"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/docker/*"

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "files/data/mqtt/config/mosquitto.conf", dest: "/var/docker-Compose/data/mqtt/config/mosquitto.conf" }
  - { src: "files/data/mqtt/config/passwords.mqtt", dest: "/var/docker-Compose/data/mqtt/config/passwords.mqtt" }
  - { src: "files/data/zigbee/configuration.yaml", dest: "/var/docker-Compose/data/zigbee/configuration.yaml" }
  - { src: "files/data/node-red/settings.js", dest: "/var/docker-Compose/data/node-red/settings.js" }
  - { src: "files/data/node-red/package.json", dest: "/var/docker-Compose/data/node-red/package.json" }
  - { src: "files/data/node-red/flows.json", dest: "/var/docker-Compose/data/node-red/flows.json" }
  - { src: "files/data/node-red/entrypoint.sh", dest: "/var/docker-Compose/data/node-red/entrypoint.sh" }

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: /var/docker-Compose
    remove_orphans: true
    restarted: true
    files:
    - docker-zigbee.yml
  become_user : pi
