---
- name: create /var/dockerCompose
  file:
    path: /var/dockerCompose
    recurse: yes
    mode: 0755
    owner: pi
    group: pi

- name: copy Docker Compose files
  copy:
    src: "{{ item }}"
    dest: "/var/dockerCompose"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/*"

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: /var/dockerCompose
    files:
    - docker-mqtt.yml
    - docker-zigbee.yml
  become_user : pi