---
- name: create /var/dockerCompose
  file:
    path: /var/dockerCompose
    recurse: yes
    mode: 0755
    owner: pi
    group: pi

- name: copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /var/dockerCompose/{{ item }}
    mode: 0755
    owner: pi
    group: pi
  loop:
  - docker-compose.yml  


# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: /var/dockerCompose
    files:
    - docker-compose.yml
    