---
- name: create /var/docker-Compose
  file:
    path: /var/docker-Compose
    recurse: yes
    mode: 0755
    owner: pi
    group: pi

- name: copy Docker Compose files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-Compose"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/docker/*"

- name: copy mosquitto.conf
  copy:
    src: "mosquitto.conf"
    dest: "/var/docker-Compose/data/mqtt/config"
    mode: 0755
    owner: pi
    group: pi

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  docker_compose:
    project_src: /var/docker-Compose
    files:
    - docker-zigbee.yml
  become_user : pi
