--- 
- name: create /var/docker-compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
    - "/var/docker-compose/data"
    - "/var/docker-compose/data/mqtt/config"
    - "/var/docker-compose/data/zigbee"
    - "/var/docker-compose/data/node-red"
    - "/var/docker-compose/data/home-assistant"
    - "/var/docker-compose/data/nginx/html"
    - "/var/docker-compose/data/nginx/sites-enabled"
    - "/var/docker-compose/data/postgres"
    - "/var/docker-compose/data/home-assistant"

- name: copy Docker Compose files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-compose"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/docker/*"

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "files/data/mqtt/config/mosquitto.conf", dest: "/var/docker-compose/data/mqtt/config/mosquitto.conf" }
  - { src: "files/data/mqtt/config/passwords.mqtt", dest: "/var/docker-compose/data/mqtt/config/passwords.mqtt" }
  - { src: "files/data/zigbee/configuration.yaml", dest: "/var/docker-compose/data/zigbee/configuration.yaml" }
  - { src: "files/data/node-red/settings.js", dest: "/var/docker-compose/data/node-red/settings.js" }
  - { src: "files/data/node-red/package.json", dest: "/var/docker-compose/data/node-red/package.json" }
  - { src: "files/data/node-red/flows.json", dest: "/var/docker-compose/data/node-red/flows.json" }
  - { src: "files/data/node-red/entrypoint.sh", dest: "/var/docker-compose/data/node-red/entrypoint.sh" }
  - { src: "files/data/nginx/html/index.html", dest: "/var/docker-compose/data/nginx/html/index.html" }
  - { src: "files/data/nginx/html/schuur.jpg", dest: "/var/docker-compose/data/nginx/html/schuur.jpg" }
  - { src: "files/data/nginx/html/schuur.png", dest: "/var/docker-compose/data/nginx/html/schuur.png" }
  - { src: "files/data/nginx/sites-enabled/default", dest: "/var/docker-compose/data/nginx/sites-enabled/default" }
  - { src: "files/data/postgres/.env", dest: "/var/docker-compose/data/postgres/.env" }
  - { src: "files/data/home-assistant/configuration.yaml", dest: "/var/docker-compose/data/home-assistant/configuration.yaml" }

- name: Check for weather-icons exists 
  stat:
    path: /var/docker-compose/data/node-red/weather-icons
  register: p1

- name: download weather-icons
  git:
    repo: https://github.com/Paul-Reed/weather-icons-lite.git  
    dest: /var/docker-compose/data/node-red/
    force: yes
  when: not p1.stat.exists

git:

- name: deploy Docker Compose stack
  shell:
    cmd: "docker-compose up -d"
  args:
    chdir:  /var/docker-compose
  become: pi