---
- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes
    
- name: Install Home Assistant applications
  apt: 
    name: [ "python3", "python3-dev", "python3-venv", "python3-pip", "libffi-dev", "libssl-dev", "libjpeg-dev", "zlib1g-dev", "autoconf", "build-essential", "libopenjp2-7", "libtiff5" ]

- name: download Python-3.8.0.tgz
  get_url:
    url: https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
    dest: /tmp
    mode: 0760

- name: untar
  shell: |
    tar zxf Python-3.8.0.tgz
  args:
    chdir: /tmp
    creates: "/usr/local/bin/python3.8"

- name: ./configure --enable-optimizations
  shell: "{{ item }}"
  with_items:
    - "sudo ./configure --enable-optimizations"
    - "sudo make -j 4"
    - "sudo make altinstall"
    - "python3.8 --version"
    - "echo "alias python3.8=/usr/local/bin/python3.8" >> ~/.bashrc"
    - "source ~/.bashrc"
    - "python --version"
  args:
    chdir: /tmp/Python-3.8.0
    creates: "/usr/local/bin/python3.8"


- name: Ensure group "homeassistant" exists
  group:
    name: homeassistant
    state: present

- name: sudo without password for homeassistant group
  copy:
    content: '%homeassistant ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/homeassistant_nopasswd
    mode: 0440

- name: Add the user 'homeassistant' with primary group of 'dialout'
  user:
    name: homeassistant
    comment: homeassistant user
    group: homeassistant
    groups: root, dialout

- name: create /srv/homeassistant
  file:
    path: /srv/homeassistant
    recurse: yes
    mode: 0760
    owner: homeassistant
    group: homeassistant

- name: create to a virtual environment for Home Assistant Core
  shell:
    cmd: "python3.8 -m venv ."
#  become_user: homeassistant
  args:
    chdir: /srv/homeassistant

- name: change to a virtual environment for Home Assistant Core
  shell:
    cmd: "source bin/activate"
#  become_user: homeassistant
  args:
    chdir: /srv/homeassistant

- name: Install required Python package
  shell:
    cmd: "python3 -m pip install wheel"
#  become_user: homeassistant
  args:
    chdir: /srv/homeassistant    

- name: Install homeassistant
  shell:
    cmd: "pip3 install homeassistant"
#  become_user: homeassistant
  args:
    chdir: /srv/homeassistant     

- name: Start Home Assistant Core for the first time.
  shell:
    cmd: "hass"
#  become_user: homeassistant
  args:
    chdir: /srv/homeassistant     
